# iterate over requirements.txt generated by conda list and install from appropriate repo --export inside env
#input is requirements file
#must have conda installed and pip too


var1=$1
echo 'pulling packages from' $1
awk 'NR>3' $var1 > tmp.txt
conda install pip
while read line; 
do  
	#var4=$(echo $line | awk '{printf $4}')
	#echo $var4
	var4=$(echo $line | awk '{printf $4}') 

	if [[ "$var4" = "pypi" ]];
	then
	# # 	#var3=$(echo $line | awk '{printf $4}')
	  	echo  'pip here'
	    echo $line | pip install $(awk '{printf $1}')
	else
	 	echo 'conda repo'
	    echo $line | conda install $(awk '{printf $4"::"$1 }') 
	  fi

done < tmp.txt
rm tmp.txt
